### ISSUE TITLE
Where do you store 8-bit weights during training in the code?

### ISSUE THREAD

**Issue by WeicongChen** [boluoweifenda/WAGE#2]
Nice work! 
In your paper, you said:
> Weights are stored with 8-bit integers during training and ternarized by two constant symmetrical thresholds during inference.

But I can't find where you do the operation "store 8-bit weights" in the code. Can you point out for me? Thank you!

**Comment by boluoweifenda** [comment]
@juicecwc 
It is in the Top.py file
https://github.com/boluoweifenda/WAGE/blob/3b1d4cba0f4ea59457f050dea3403759289b73d4/source/Top.py#L16

**Comment by WeicongChen** [comment]
Sorry, I still can't understand. The line you point out is quantizing gradients to 8-bit, but it won't quantize weights to 8-bit. In my understanding, weights are either 32-bit or 2-bit in your code. Is my understanding right?

**Comment by boluoweifenda** [comment]
@juicecwc 
Sorry, I forgot to notice that we quantize weight to ternary values at the beginning:
https://github.com/boluoweifenda/WAGE/blob/3b1d4cba0f4ea59457f050dea3403759289b73d4/source/Top.py#L112
Since the updates of weight (gradients) are in 8 bits, the overall bitwidth of weight is 8-bit during training.
Please refer to the comment in:
https://github.com/boluoweifenda/WAGE/blob/3b1d4cba0f4ea59457f050dea3403759289b73d4/source/Top.py#L64

**Comment by WeicongChen** [comment]
I see. Thank you!
